### ISSUE TITLE
AI서버 기본 작동 TODO

### ISSUE THREAD

**Issue by CHOUMnote** [neoman-omyeon-go/BigsasimiServer-AI#1]
### 해당 서버 기본 로직 작동을 위한 리스트

- [ ] 테스트 모델 작동
- [ ] fast + 모델 연결 확인
- [ ] 메인 서버와 연결 및 작동 확인

AI서버 관련 문의는 코멘트로...
